export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAIL = 'CREATE_LIST_FAIL';

export const ALL_LIST_REQUEST = 'ALL_LIST_REQUEST';
export const ALL_LIST_SUCCESS = 'ALL_LIST_SUCCESS';
export const ALL_LIST_FAIL = 'ALL_LIST_FAIL';

export const SINGLE_LIST_REQUEST = 'SINGLE_LIST_REQUEST';
export const SINGLE_LIST_SUCCESS = 'SINGLE_LIST_SUCCESS';
export const SINGLE_LIST_FAIL = 'SINGLE_LIST_FAIL';



