export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const GET_BIO_REQUEST = 'GET_BIO_REQUEST';
export const GET_BIO_SUCCESS = 'GET_BIO_SUCCESS';
export const GET_BIO_FAIL = 'GET_BIO_FAIL';

export const UPDATE_BIO_REQUEST = 'UPDATE_BIO_REQUEST';
export const UPDATE_BIO_SUCCESS = 'UPDATE_BIO_SUCCESS';
export const UPDATE_BIO_FAIL = 'UPDATE_BIO_FAIL';

export const GET_PIC_REQUEST = 'GET_PIC_REQUEST';
export const GET_PIC_SUCCESS = 'GET_PIC_SUCCESS';
export const GET_PIC_FAIL = 'GET_PIC_FAIL';

export const UPLOAD_PIC_REQUEST = 'UPLOAD_PIC_REQUEST';
export const UPLOAD_PIC_SUCCESS = 'UPLOAD_PIC_SUCCESS';
export const UPLOAD_PIC_FAIL = 'UPLOAD_PIC_FAIL';
